# Generated by Django 4.1.6 on 2023-03-06 07:31

from django.db import migrations, models
import swebooking.models


class Migration(migrations.Migration):

    dependencies = [
        ('swebooking', '0003_alter_tablebooking_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_date_time',
            field=models.DateTimeField(validators=[swebooking.models.validate_datetime]),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
